CREATE TABLE COMPRAS ( 
    ID_COMPRA  INTEGER  NOT NULL,
    PRECIO     NUMBER(10,2) NOT NULL, 
    USUARIO_ID INTEGER NOT NULL 
);

ALTER TABLE COMPRAS 
ADD CONSTRAINT COMPRAS_PK PRIMARY KEY (ID_COMPRA);

CREATE TABLE USUARIO ( 
    USUARIO_ID  INTEGER  NOT NULL , 
    USUARIO_NAME VARCHAR2 (50 CHAR)  NOT NULL 
);

ALTER TABLE USUARIO 
ADD CONSTRAINT USUARIO_PK PRIMARY KEY ( USUARIO_ID ) ;

ALTER TABLE COMPRAS 
ADD CONSTRAINT COMPRAS_USUARIO_FK FOREIGN KEY (USUARIO_ID) 
REFERENCES USUARIO( USUARIO_ID );