services:
  db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: "admin_202110509"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
    driver: local